# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ndlwill/Specs.git'


platform :ios, ‘8.0’

target 'NDL_Category' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NDL_Category
pod 'SDWebImage'
pod 'YYKit'
#pod 'YYText'
#pod 'YYWebImage'
#pod 'AFNetworking'
pod 'YTKNetwork'
pod 'LKDBHelper'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'AMapLocation', '~> 2.6.0'

# pod 'DrawLib', '~> 1.0.1'
# pod 'DrawLib', '~> 1.0.0'
pod 'DrawLib'

# 添加本地lib develop
#pod 'DrawLib', :path => '../../DrawLib'
end
