# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ndlwill/Specs.git'

platform :ios, ‘8.0’

target 'NDL_Category' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NDL_Category
pod 'SDWebImage'
pod 'YYKit'
#pod 'YYText'
#pod 'YYWebImage'
#pod 'AFNetworking'
pod 'YTKNetwork'
pod 'LKDBHelper'
pod 'PinYin4Objc', '~> 1.1.1'
pod 'AMapLocation'
pod 'SSZipArchive'
pod 'GCDWebServer'
pod 'MBProgressHUD'
pod 'DateTools'
pod 'CTMediator'
pod 'MQTTClient'

pod 'AMap3DMap'

pod 'CocoaAsyncSocket', '~> 7.6.3'

# facebook
pod 'FBMemoryProfiler'
pod 'fishhook'

pod 'FLEX', '~> 2.0', :configurations => ['Debug']
#pod 'Reveal-SDK', :configurations => ['Debug']

pod 'ReactiveObjC'
pod 'CocoaLumberjack'
pod 'FDFullscreenPopGesture'
pod 'WCDB'
pod 'PLCrashReporter'

# realm
# pod 'Realm'

# pod 'DrawLib', '~> 1.0.1'
# pod 'DrawLib', '~> 1.0.0'
pod 'DrawLib'

# =====添加本地lib develop=====
# DrawLib是DrawLib.podspec的名字  path是DrawLib.podspec相对于的路径，相对于Podfile文件的路径
#pod 'DrawLib', :path => '../../DrawLib'
end

# https://www.rubydoc.info/gems/cocoapods
# do ~ end 部分就是所谓的块. 除 do ~ end 这一形式外, 我们也可以使用 { ~ } 这种形式
post_install do |installer|
  # show_installer installer
  
  puts "==#{installer}==" # Pod::Installer
  puts "==#{installer.pods_project}==" # Pod::Project

  project_path = 'NDL_Category.xcodeproj'    # 工程的全路径

  # pods_project -> `Pods/Pods.xcodeproj`
  installer.pods_project.targets.each do |target|
    puts "pods_project: target:#{target} target.name:#{target.name}"
  end

  puts "=============================="

=begin
Xcodeproj:
https://www.rubydoc.info/gems/xcodeproj/Xcodeproj
CocoaPods 官方提供的用于修改 xcode 工程文件的 ruby 类库

gem install xcodeproj
=end
  project = Xcodeproj::Project.open(project_path)
  puts "==#{project}==" # Xcodeproj::Project  path:`/Users/ndl/Desktop/iOS/NDL_Category/NDL_Category.xcodeproj`

  project.targets.each do |target|
    puts "project: target:#{target} target.name:#{target.name}"
    # build_phases
    if !exist_run_swiftlint_script target
      
    end


    # build_settings
    # target.build_configurations.each do |configuration|
    #   puts "==#{configuration}==" # ==Debug==, ==Release==
    #   if configuration.name == 'Debug'
    #     puts "==#{configuration.build_settings}=="
    #     # configuration.build_settings["HEADER_SEARCH_PATHS"] = "XXX"
    #   end
    # end
    
  end
  
  project.save()
end

# 判断是否已经添加了"Run SwiftLint Script"
def exist_run_swiftlint_script(target)
  target.build_phases.each do |build_phase|
    puts "build_phase: #{build_phase}"
    puts "build_phase.class: #{build_phase.class}"
    # puts "build_phase.methods: #{build_phase.methods}"
    # puts "build_phase.instance_variables: #{build_phase.instance_variables}"

    if String(build_phase) == 'Run SwiftLint Script'
      return true
    end
  end
  
  return false
end

def show_installer(installer)
  puts "##### show_installer start #####"
  
  # 为了打印的日志方便查看，使用╟符号修饰
  puts "╟ installer"
  puts "  ======== installer.instance_variables ========"
  # 获取属性名称列表，并遍历
  installer.instance_variables.each do |variableName|
    # 打印属性名称
    puts "  ╟ #{variableName}"
  end
  
  puts "  ======== installer.public_methods ========"
  # 获取方法名称列表，并遍历
  installer.public_methods.each do |method|
    # 打印方法名称
    puts "  ╟ #{method}"
  end
  puts "##### show_installer end #####"
end