# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftDemo
  pod 'R.swift'
  pod 'Moya-ObjectMapper', '>= 2.8'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'ObjectMapper'
  pod 'RxDataSources'
  pod 'RxAlamofire'
  pod 'SnapKit'
  

end
