source "https://rubygems.org"

gem "fastlane"
gem "cocoapods"
gem "abbrev"


# It seems like you wanted to load some plugins, however they couldn't be loaded
# 打印plugins_path 然后将默认的plugins_path = File.join(File.dirname(__FILE__), '.', 'Pluginfile')  其中的.改为fastlane，即Pluginfile所在的文件夹，然后bundle install
plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
puts "plugins_path = #{plugins_path}"
eval_gemfile(plugins_path) if File.exist?(plugins_path)
