concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "YD-Tech-PC-nidongle-G05-02-00009.local"
  url = "https://jihulab.com"
  id = 36762
  token = "glrt-t3_TuKw7x_MMHqqvj9hpnGR"
  token_obtained_at = 2025-04-25T07:08:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  builds_dir = "/Users/youdun-ndl/gitlab_builds/builds"
  [runners.custom_build_dir]
    enabled = true
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
